# Generated by Django 3.1.3 on 2020-12-03 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_closet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closet',
            name='name',
        ),
    ]
