# Generated by Django 3.1.3 on 2020-12-04 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_closet', '0003_closet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet',
            name='desc',
            field=models.CharField(default='Description', max_length=1000),
        ),
        migrations.AddField(
            model_name='clothes',
            name='brand',
            field=models.CharField(default='Brand', max_length=30),
        ),
        migrations.AddField(
            model_name='clothes',
            name='closet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_closet.closet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothes',
            name='clothes_name',
            field=models.CharField(default='Name', max_length=30),
        ),
        migrations.AddField(
            model_name='clothes',
            name='color',
            field=models.CharField(default='Color', max_length=30),
        ),
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.CharField(default='No Image', max_length=1000),
        ),
        migrations.AddField(
            model_name='clothes',
            name='size',
            field=models.CharField(default='Size', max_length=30),
        ),
        migrations.AddField(
            model_name='clothes',
            name='type_cloth',
            field=models.CharField(default='Cloth Type', max_length=30),
        ),
        migrations.AlterField(
            model_name='closet',
            name='name',
            field=models.CharField(default='My Closet', max_length=200),
        ),
    ]
