# Generated by Django 3.1.3 on 2020-12-04 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_closet', '0004_auto_20201203_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='closet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_closet.closet'),
        ),
    ]
